apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/mmorhun-tenant/devfile-sample-go-basic/devfile-sample-go-basic@sha256:9aa68f652c7d26b2471ac54df148da5d9aab3f70643623960e0e52f895ea354e
        name: my-go
        resources: {}
status: {}
